// models.js generated by update_model_js.py. EDIT WITH CAUTION!
var model_index = [
		{title: "0 Horizontale worp", url: "modellen/horizontale_worp.xml"},
		{title: "1 Kogelbaanmodel", url: "modellen/kogelbaan.xml"},
		{title: "2 Kogelbaanmodel met luchtweerstand", url: "modellen/kogelbaan_luchtweerstand.xml"},
		{title: "3 Satellietmodel", url: "modellen/satelliet.xml"},
		{title: "Kogelstoten", url: "modellen/kogelstoten.xml"},
		{title: "Kogelstoten UITWERKING", url: "modellen/kogelstoten_antwoord.xml"},
		{title: "Satellietbaanmodel", url: "modellen/satellietbaan.xml"},
		{title: "Satellietbaanmodel UITWERKING", url: "modellen/satellietbaan_antwoord.xml"},
];